### ISSUE TITLE
3 задание 

### ISSUE THREAD

**Issue by DmitriiMelnikOnix** [irnity/ReactIntership#5]
По 3 заданию жду второй способ сортировки, обновление обьектов через spread оператор, два уровня вложенности для обьектов

**Comment by irnity** [comment]
Я переписал свое 3е задание, можешь подсказать в чем ошибка может быть, когда делаешь edit то что второго уровня вложенности не могу переписать

**Comment by DmitriiMelnikOnix** [comment]
Проблема в том этих двух строках 
```
    const newFormData = { ...editFormData }
    newFormData[fieldName] = fieldValue
```

Если `fieldName` равно 'firstName' то ты пропускаешь вложенность и добавляешь новое поле в `newFormData`
И у тебя получается что-то вроде
```
{
  firstName: "",
  secondName: "",
  name: {
    firstName: "",
    secondName: "",
  },
  address: "",
  phoneNumber: "",
  email: "",
}
```
